import p1 from "../assets/p1.png";
import p2 from "../assets/p2.png";
import p3 from "../assets/p3.png";
import {
  FileBox,
  PackageCheck,
  ReceiptIndianRupee,
  StretchHorizontal,
} from "lucide-react";
import invoDel from "../assets/InvoiceDelivery.jpg";
import invoP from "../assets/InvoiceP.png";
import payment from "../assets/Payment.png";
import { LiaStarSolid } from "react-icons/lia";
import { CiCreditCard1 } from "react-icons/ci";
import { FaRegCircleUser, FaRegFileLines } from "react-icons/fa6";
import { MdMenuBook } from "react-icons/md";
import { TbBuildingWarehouse, TbReportAnalytics } from "react-icons/tb";
import { LuFileUser } from "react-icons/lu";

export const badges = [
  {
    id: 1,
    label: "Party",
  },
  {
    id: 2,
    label: "Invoice",
  },
  {
    id: 3,
    label: "Category",
  },
  {
    id: 4,
    label: "Payment Collection",
  },
  {
    id: 5,
    label: "Item",
  },
  {
    id: 6,
    label: "Invoice Details",
  },
  {
    id: 7,
    label: "Summary",
  },
];

export const features = [
  {
    title: "Creating repeated bills?",
    img: p1,
    desc: "Automate sending of repeat bills based on a schedule of your choice",
  },
  {
    title: "Automated Billing",
    img: p2,
    desc: "Send SMS reminders to customers daily/weekly/monthly",
  },
  {
    title: "Easy Reminders & Payment",
    img: p3,
    desc: "Automatically receive notifications and collect payments",
  },
];

export const cardDetails = [
  {
    id: 1,
    img: invoP,
    label: "Automatic e-invoice generation",
  },
  {
    id: 2,
    img: invoDel,
    label: "Hassle e-way bill generation using IRN",
  },
  {
    id: 3,
    img: payment,
    label: "Easy GSTR1 reconciliation",
  },
];

export const newItemsSidebarDetails = [
  {
    id: 1,
    icon: <FileBox size={18} />,
    title: "Basic Details",
  },
  {
    id: 2,
    icon: <PackageCheck size={18} />,
    title: "Stock Details",
  },
  {
    id: 3,
    icon: <ReceiptIndianRupee size={18} />,
    title: "Pricing Details",
  },
  {
    id: 4,
    icon: <ReceiptIndianRupee size={18} />,
    title: "Party Wise Prices",
  },
  {
    id: 5,
    icon: <StretchHorizontal size={18} />,
    title: "Custom Fields",
  },
];

export const pricingPlans = [
  {
    id: 1,
    color: "[#E16733]",
    name: "Diamond Plan",
    tagline: "Essential plan for small business owners",
    monthlyPrice: 217,
    yearlyPrice: "Billed Annually ₹2599/year",

    manage: "1 Business",
    access: "1 User + 1 CA",
    Auto: "data across unlimited devices",
    accessOn: ["Android", "iOS", "Web"],
    feature: "Features Exclusive to",
    features: [
      "Custom Invoice Themes",
      "Generate and print barcodes (A4 only)",
      "Create your Online Store",
      "Add your CA",
      "Desktop App for Fast and Convenient Use",
      "E-way Bills",
      "Generate e-Invoices",
      "POS Billing",
      "Staff Attendance & Payroll",
      "Create Unlimited Godowns",
      "User Activity Tracker",
      "Automated Billing",
      "WhatsApp & SMS Marketing",
      "Loyalty and Rewards",
      "Bulk Download & Bulk Print Invoices",
      "Data Export to Tally",
    ],
  },
  {
    id: 2,
    color: "[#485EB0]",
    name: "Platinum Plan",
    tagline: "More users, more flexibility, and a Desktop app",
    monthlyPrice: 250,
    originalMonthlyPrice: 417,
    yearlyPrice: "Billed Annually ₹2999/year",

    manage: "2 Businesses",
    access: "3 Users + 1 CA",
    Auto: "data across unlimited devices",
    accessOn: ["Android", "iOS", "Web", "Desktop"],
    feature: "Features Exclusive to",
    features: [
      "Desktop App for Fast and Convenient Use",
      "Custom Invoice Themes",
      "E-way Bills (50/year)",
      "Staff Attendance & Payroll",
      "Create Unlimited Godowns",
      "Generate and print barcodes (A4 only)",
      "Create your Online Store",
      "WhatsApp & SMS Marketing (500 SMS/Year)",
      "Bulk Download & Bulk Print Invoices",
      "Add your CA",
      "Generate e-Invoices",
      "POS Billing",
      "User Activity Tracker",
      "Automated Billing",
      "Loyalty and Rewards",
      "Data Export to Tally",
    ],
  },
  {
    id: 3,
    color: "[#06B181]",
    name: "Enterprise Plan",
    tagline: "Fully customizable for bigger businesses",
    monthlyPrice: 417,
    originalMonthlyPrice: 667,
    yearlyPrice: "Billed Annually ₹4999/year",
    manage: "2 Businesses (Upgrade to add more)",
    access: "3 Users (Upgrade to add more) + 1 CA",
    Auto: "data across unlimited devices",
    accessOn: ["Android", "iOS", "Web", "Desktop"],
    feature: "Features Exclusive to",
    features: [
      "Desktop App for Fast and Convenient Use",
      "Custom Invoice Themes",
      "E-way Bills (Unlimited)",
      "Generate e-Invoices",
      "POS Billing (Desktop App, Web app)",
      "Staff Attendance & Payroll",
      "Create Unlimited Godowns",
      "Generate and print barcodes (A4 only)",
      "Data Export to Tally (On request)",
      "User Activity Tracker",
      "Automated Billing",
      "Create your Online Store",
      "WhatsApp & SMS Marketing (1000 SMS/Year)",
      "Loyalty and Rewards",
      "Bulk Download & Bulk Print Invoices",
      "Add your CA",
    ],
  },
];
export const pricing_Review = [
  {
    id: 1,
    name: "Vansh",
    review: `We were searching for an affordable app to manage our business operations, and this one delivers far 
        more than expected for the price. The monthly plan fits our budget, and the features are comparable to much more 
        expensive tools. Highly recommended for startups and small teams.`,
    stars: <LiaStarSolid size={18} />,
  },
  {
    id: 2,
    name: "Rohit",
    review: `After using this app for just three months, we've seen an increase in productivity and a noticeable reduction
         in operational costs. The yearly plan offers great savings, and we’re already seeing the return on investment. 
         Definitely one of the smartest purchases we’ve made for the business.`,
    stars: <LiaStarSolid size={18} />,
  },
  {
    id: 3,
    name: "Manish",
    review: `I love how the pricing adapts to different stages of business growth. We started on the entry-level plan and 
        recently upgraded to a premium one without any hassle. It’s great to have an app that grows with you, both in features
        and pricing.`,
    stars: <LiaStarSolid size={18} />,
  },
];

export const LandingPagePricingPlan = [
  {
    id: 1,
    name: "Diamond",
    tagline: "Essential plan for small business owners",
    monthly: "₹300",
    offeredprice: "₹217",
    yearlyprice: "Pay ₹3599 ₹2599/year.Billed annually",
    button1text: "Start Free Trial",

    feature: [
      "Manage 1 Business",

      "Access for 1 User + 1 CA",

      "Auto sync data across unlimited devices",

      "Access on Android, iOS & Web",
    ],
    featuresheading: "Includes Silver, plus:",
    features: [
      "Custom Invoice Themes",
      "Create your Online Store",
      "Generate, print(A4 printer) & scan barcode",
    ],
  },

  {
    id: 2,
    name: "Platinum",
    tagline: "More users, more flexibility, and a Desktop app",
    monthly: "₹500",
    offeredprice: "₹250",
    yearlyprice: "Pay ₹5999 ₹2999/year. Billed annually",
    button1text: "Start Free Trial",
    button2text: "Talk to Sales",
    feature: [
      "Manage 2 Business",

      "Access for 3 Users + 1 CA",

      "Auto sync data across unlimited devices",

      "Access on Android, iOS, Web & Web",
    ],
    featuresheading: "Includes Diamond, plus:",
    features: [
      "Desktop App",
      "SMS + Whatsapp marketing (500 messages/ Year)",
      "E-Way Bills (50/Year)",
      "Staff Attendance & Payroll",
      "Godowns (Unlimited)",
      "Print Barcode (Label printer)",
      "Bulk Download & Bulk Print Invoices",
    ],
  },

  {
    id: 3,
    name: "Enterprise",
    tagline: "Fully customizable for bigger businesses",
    monthly: "₹750",
    offeredprice: "₹417",
    yearlyprice: "Pay ₹8999 ₹4999/year. Billed annually",

    button2text: "Talk to Sales",
    feature: [
      "Manage 2 Businesses (Upgrade to add more)",

      "Access for 3 Users (Upgrade to add more) + 1 CA",

      "Auto sync data across unlimited devices",

      "Access on Android, iOS, Web & Web",
    ],
    featuresheading: "Includes Platinum, plus:",
    features: [
      "E-Way Bills (Unlimited)",
      "Generate e-Invoicing",
      "Loyalty & Rewards",
      "Automate Recurring Billing",
      "POS Billing (Desktop App, Web app)",
      "Data Export to tally (on request)",
      "User Activity Tracker",
    ],
  },
];

export const states = [
  "Enter state",
  "Andaman & Nicobar Islands",
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chandigarh",
  "Chhasttisgarh",
  "Dadra & Nagar Haveli & Daman & Diu",
  "Delhi",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jammu & Kashmir",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Ladakh",
  "Lakshadweep",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalay",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Puducherry",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
  "Foreign Country",
  "Other Territory",
];

export const statesAndCities = [
  {
    state: "Andhra Pradesh",
    cities: ["Hyderabad", "Visakhapatnam", "Vijayawada", "Guntur", "Tirupati"],
  },
  {
    state: "Arunachal Pradesh",
    cities: ["Itanagar", "Tawang", "Pasighat", "Ziro"],
  },
  {
    state: "Assam",
    cities: ["Guwahati", "Dibrugarh", "Jorhat", "Silchar", "Tezpur"],
  },
  {
    state: "Bihar",
    cities: ["Patna", "Gaya", "Darbhanga", "Bhagalpur", "Muzaffarpur"],
  },
  {
    state: "Chhattisgarh",
    cities: ["Raipur", "Bhilai", "Bilaspur", "Korba", "Durg"],
  },
  {
    state: "Goa",
    cities: ["Panaji", "Margao", "Mapusa", "Vasco da Gama"],
  },
  {
    state: "Gujarat",
    cities: ["Ahmedabad", "Surat", "Vadodara", "Rajkot", "Bhavnagar"],
  },
  {
    state: "Haryana",
    cities: ["Chandigarh", "Gurugram", "Faridabad", "Panipat", "Karnal"],
  },
  {
    state: "Himachal Pradesh",
    cities: ["Shimla", "Dharamshala", "Mandi", "Solan", "Bilaspur"],
  },
  {
    state: "Jharkhand",
    cities: ["Ranchi", "Jamshedpur", "Dhanbad", "Bokaro", "Hazaribagh"],
  },
  {
    state: "Karnataka",
    cities: ["Bengaluru", "Mysuru", "Mangaluru", "Hubballi", "Belagavi"],
  },
  {
    state: "Kerala",
    cities: ["Thiruvananthapuram", "Kochi", "Kozhikode", "Thrissur", "Kollam"],
  },
  {
    state: "Madhya Pradesh",
    cities: ["Bhopal", "Indore", "Gwalior", "Jabalpur", "Ujjain"],
  },
  {
    state: "Maharashtra",
    cities: ["Mumbai", "Pune", "Nagpur", "Nashik", "Aurangabad"],
  },
  {
    state: "Manipur",
    cities: ["Imphal", "Thoubal", "Churachandpur", "Ukhrul"],
  },
  {
    state: "Meghalaya",
    cities: ["Shillong", "Tura", "Jowai", "Baghmara"],
  },
  {
    state: "Mizoram",
    cities: ["Aizawl", "Lunglei", "Champhai", "Serchhip"],
  },
  {
    state: "Nagaland",
    cities: ["Kohima", "Dimapur", "Mokokchung", "Tuensang"],
  },
  {
    state: "Odisha",
    cities: ["Bhubaneswar", "Cuttack", "Rourkela", "Sambalpur", "Berhampur"],
  },
  {
    state: "Punjab",
    cities: ["Chandigarh", "Amritsar", "Ludhiana", "Jalandhar", "Patiala"],
  },
  {
    state: "Rajasthan",
    cities: ["Jaipur", "Jodhpur", "Udaipur", "Kota", "Bikaner"],
  },
  {
    state: "Sikkim",
    cities: ["Gangtok", "Namchi", "Gyalshing"],
  },
  {
    state: "Tamil Nadu",
    cities: ["Chennai", "Coimbatore", "Madurai", "Tiruchirappalli", "Salem"],
  },
  {
    state: "Telangana",
    cities: ["Hyderabad", "Warangal", "Karimnagar", "Nizamabad"],
  },
  {
    state: "Tripura",
    cities: ["Agartala", "Udaipur", "Kailasahar"],
  },
  {
    state: "Uttar Pradesh",
    cities: ["Lucknow", "Kanpur", "Varanasi", "Agra", "Meerut"],
  },
  {
    state: "Uttarakhand",
    cities: ["Dehradun", "Haridwar", "Rishikesh", "Nainital"],
  },
  {
    state: "West Bengal",
    cities: ["Kolkata", "Siliguri", "Howrah", "Asansol"],
  },
  // Union Territories
  {
    state: "Andaman and Nicobar Islands",
    cities: ["Port Blair"],
  },
  {
    state: "Chandigarh",
    cities: ["Chandigarh"],
  },
  {
    state: "Dadra and Nagar Haveli and Daman and Diu",
    cities: ["Daman", "Diu", "Silvassa"],
  },
  {
    state: "Delhi",
    cities: ["New Delhi", "Delhi"],
  },
  {
    state: "Jammu and Kashmir",
    cities: ["Srinagar", "Jammu"],
  },
  {
    state: "Ladakh",
    cities: ["Leh", "Kargil"],
  },
  {
    state: "Lakshadweep",
    cities: ["Kavaratti"],
  },
  {
    state: "Puducherry",
    cities: ["Puducherry", "Karaikal", "Mahe", "Yanam"],
  },
];

export const dashboardSinglePartyMenus = [
  {
    id: 1,
    title: "Transactions",
    icon: <CiCreditCard1 />,
  },
  {
    id: 2,
    title: "Profile",
    icon: <FaRegCircleUser />,
  },
  {
    id: 3,
    title: "Ledger (Statement)",
    icon: <MdMenuBook />,
  },
  {
    id: 4,
    title: "Item Wise Report",
    icon: <TbReportAnalytics />,
  },
];

export const gstRates = [
  { id: 0, label: "None" },
  { id: 1, label: "Exempted" },
  { id: 2, label: "GST @ 0%" },
  { id: 3, label: "GST @ 0.1%" },
  { id: 4, label: "GST @ 0.25%" },
  { id: 5, label: "GST @ 1.5%" },
  { id: 6, label: "GST @ 3%" },
  { id: 7, label: "GST @ 5%" },
  { id: 8, label: "GST @ 6%" },
  { id: 9, label: "GST @ 12%" },
  { id: 10, label: "GST @ 13.8%" },
  { id: 11, label: "GST @ 18%" },
  { id: 12, label: "GST @ 14% + cess @ 12%" },
  { id: 13, label: "GST @ 28%" },
  { id: 14, label: "GST @ 28% + Cess @ 5%" },
  { id: 15, label: "GST @ 28% + Cess @ 12%" },
  { id: 16, label: "GST @ 28% + Cess @ 36%" },
  { id: 17, label: "GST @ 28% + Cess @ 60%" },
];

export const uomList = [
  { id: 1, label: "Accessories", code: "ACS" },
  { id: 2, label: "Thousands", code: "THD" },
  { id: 3, label: "Aaaaaaaaaaa", code: "G NEX" },
  { id: 4, label: "Aana", code: "ANA" },
  { id: 5, label: "Accessories", code: "ACS" },
  { id: 6, label: "Acre", code: "AC" },
  { id: 7, label: "Adult", code: "ADL" },
  { id: 8, label: "Ampoule", code: "AMP" },
  { id: 9, label: "Bags", code: "BAG" },
  { id: 10, label: "Bale", code: "BAL" },
  { id: 11, label: "Balls", code: "BALL" },
  { id: 12, label: "Barni", code: "BAR" },
  { id: 13, label: "Barrel", code: "BRL" },
  { id: 14, label: "Billions Of Units", code: "BOU" },
  { id: 15, label: "Blister", code: "BLISTER" },
  { id: 16, label: "Bolus", code: "BOLUS" },
  { id: 17, label: "Book", code: "BK" },
  { id: 18, label: "Bora", code: "BOR" },
  { id: 19, label: "Bottles", code: "BTL" },
  { id: 20, label: "Box", code: "BOX" },
  { id: 21, label: "Brass", code: "BRASS" },
  { id: 22, label: "Brick", code: "BRICK" },
  { id: 23, label: "Buckets", code: "BCK" },
  { id: 24, label: "Buckles", code: "BKL" },
  { id: 25, label: "Bunches", code: "BUN" },
  { id: 26, label: "Bundles", code: "BDL" },
  { id: 27, label: "Butts", code: "BTS" },
  { id: 28, label: "Cans", code: "CAN" },
  { id: 29, label: "Cap", code: "CAP" },
  { id: 30, label: "Capsules", code: "CPS" },
  { id: 31, label: "Carat", code: "CT" },
  { id: 32, label: "Carats", code: "CTS" },
  { id: 33, label: "Card", code: "CARD" },
  { id: 34, label: "Cartons", code: "CTN" },
  { id: 35, label: "Case", code: "CASE" },
  { id: 36, label: "Centimeter", code: "CMS" },
  { id: 37, label: "Cents", code: "CNT" },
  { id: 38, label: "Ch", code: "CHAIN" },
  { id: 39, label: "Child", code: "CLD" },
  { id: 40, label: "Choka", code: "CHOKA" },
  { id: 41, label: "Chudi", code: "CHUDI" },
  { id: 42, label: "Cloth", code: "CLT" },
  { id: 43, label: "Coil", code: "COIL" },
  { id: 44, label: "Container", code: "CONT" },
  { id: 45, label: "Copy", code: "COPY" },
  { id: 46, label: "Course", code: "COURSE" },
  { id: 47, label: "Crate", code: "CRT" },
  { id: 48, label: "Cream", code: "CRM" },
  { id: 49, label: "Cubic Centimeter", code: "CCM" },
  { id: 50, label: "Cubic Feet", code: "CUFT" },
  { id: 51, label: "Cubic Feet Per Minute", code: "CFM" },
  { id: 52, label: "Cubic Foot", code: "CFT" },
  { id: 53, label: "Cubic Meter", code: "CBM" },
  { id: 54, label: "Cup", code: "CUP" },
  { id: 55, label: "Cv", code: "CV" },
  { id: 56, label: "Daily", code: "DAILY" },
  { id: 57, label: "Dangler", code: "DANGLER" },
  { id: 58, label: "Days", code: "DAY" },
  { id: 59, label: "Daze", code: "DEZ" },
  { id: 60, label: "Decimeter", code: "DMTR" },
  { id: 61, label: "Dozen", code: "DOZ" },
  { id: 62, label: "Drop", code: "DROP" },
  { id: 63, label: "Drum", code: "DRM" },
  { id: 64, label: "Ea", code: "EA" },
  { id: 65, label: "Each", code: "EACH" },
  { id: 66, label: "Feet", code: "FT" },
  { id: 67, label: "Feet Square", code: "FT2" },
  { id: 68, label: "Finger", code: "FNGR" },
  { id: 69, label: "Fit", code: "FIT" },
  { id: 70, label: "Fold", code: "FLD" },
  { id: 71, label: "Free", code: "FREE" },
  { id: 72, label: "Fts", code: "FTS" },
  { id: 73, label: "Full Plate", code: "FP" },
  { id: 74, label: "Gel", code: "GEL" },
  { id: 75, label: "Glasses", code: "GLS" },
  { id: 76, label: "Grams", code: "GMS" },
  { id: 77, label: "Great Gross", code: "GGR" },
  { id: 78, label: "Gross", code: "GRS" },
  { id: 79, label: "Gross Yards", code: "GYD" },
  { id: 80, label: "Half", code: "HF" },
  { id: 81, label: "Half Plate", code: "H.P." },
  { id: 82, label: "Hanger", code: "HEGAR" },
  { id: 83, label: "Hangers", code: "HANGER" },
  { id: 84, label: "Hectare", code: "HA" },
  { id: 85, label: "Helmet", code: "HMT" },
  { id: 86, label: "Horsepower", code: "HP" },
  { id: 87, label: "Hours", code: "HRS" },
  { id: 88, label: "Ijn", code: "INJECTION" },
  { id: 89, label: "Inches", code: "IN" },
  { id: 90, label: "Inj", code: "INJECTION" },
  { id: 91, label: "Insertion", code: "INS" },
  { id: 92, label: "Item Id", code: "ITEM ID" },
  { id: 93, label: "Jars", code: "JAR" },
  { id: 94, label: "Jhal", code: "JL" },
  { id: 95, label: "Jhola", code: "JO" },
  { id: 96, label: "Jhola Jhal", code: "JHL" },
  { id: 97, label: "Job", code: "JOB" },
  { id: 98, label: "Katta", code: "KT" },
  { id: 99, label: "Kilograms", code: "KGS" },
  { id: 100, label: "Kiloliter", code: "KLR" },
  { id: 101, label: "Kilometre", code: "KME" },
  { id: 102, label: "Kilometres", code: "KMS" },
  { id: 103, label: "Kilovolt-amp", code: "KVA" },
  { id: 104, label: "Kilowatt", code: "KW" },
  { id: 105, label: "Kit", code: "KIT" },
  { id: 106, label: "Ladi", code: "LAD" },
  { id: 107, label: "Length", code: "LENG" },
  { id: 108, label: "Libra Pondo", code: "LBS" },
  { id: 109, label: "Litre", code: "LTR" },
  { id: 110, label: "Lot", code: "LOT" },
  { id: 111, label: "Lump Sum", code: "LS" },
  { id: 112, label: "Man-days", code: "MAN-DAY" },
  { id: 113, label: "Mark", code: "MRK" },
  { id: 114, label: "Mbps", code: "MBPS" },
  { id: 115, label: "Megawatt", code: "MW" },
  { id: 116, label: "Meters", code: "MTR" },
  { id: 117, label: "Metric Million British Thermal Unit", code: "MMBTU" },
  { id: 118, label: "Metric Ton", code: "MTON" },
  { id: 119, label: "Microgram", code: "ΜG" },
  { id: 120, label: "Millicoulomb", code: "M/C" },
  { id: 121, label: "Milligram", code: "MLG" },
  { id: 122, label: "Millilitre", code: "MLT" },
  { id: 123, label: "Millimeter", code: "MM" },
  { id: 124, label: "Minutes", code: "MINS" },
  { id: 125, label: "Month", code: "UOM" },
  { id: 126, label: "Months", code: "MON" },
  { id: 127, label: "Mora", code: "MORA" },
  { id: 128, label: "Nights", code: "NIGHT" },
  { id: 129, label: "Non.", code: "NON" },
  { id: 130, label: "None", code: "NONE" },
  { id: 131, label: "Numbers", code: "NOS" },
  { id: 132, label: "Ointment", code: "OINT" },
  { id: 133, label: "Others", code: "OTH" },
  { id: 134, label: "Outer", code: "OR" },
  { id: 135, label: "Package", code: "PKG" },
  { id: 136, label: "Packets", code: "PKT" },
  { id: 137, label: "Packs", code: "PAC" },
  { id: 138, label: "Pad", code: "PAD" },
  { id: 139, label: "Pads", code: "PADS" },
  { id: 140, label: "Pages", code: "PAGE" },
  { id: 141, label: "Pair", code: "PAIR" },
  { id: 142, label: "Pairs", code: "PRS" },
  { id: 143, label: "Patta", code: "PATTA" },
  { id: 144, label: "Patti", code: "PTI" },
  { id: 145, label: "Pax", code: "PAX" },
  { id: 146, label: "Per", code: "PER" },
  { id: 147, label: "Per Day", code: "/DAY" },
  { id: 148, label: "Per Metric Ton", code: "PMT" },
  { id: 149, label: "Per Watt Peak", code: "PWP" },
  { id: 150, label: "Persons", code: "PERSON" },
  { id: 151, label: "Peti", code: "PET" },
  { id: 152, label: "Phile", code: "PHILE" },
  { id: 153, label: "Pieces", code: "PCS" },
  { id: 154, label: "Plates", code: "PLT" },
  { id: 155, label: "Pocket", code: "PCKT" },
  { id: 156, label: "Point", code: "PT" },
  { id: 157, label: "Portion", code: "PRT" },
  { id: 158, label: "Pouch", code: "POCH" },
  { id: 159, label: "Pound", code: "POUND" },
  { id: 160, label: "Puda", code: "PD" },
  { id: 161, label: "Quad", code: "QUAD" },
  { id: 162, label: "Quantity", code: "QTY" },
  { id: 163, label: "Quintal", code: "QTL" },
  { id: 164, label: "Ratti", code: "RTI" },
  { id: 165, label: "Ream", code: "REAM" },
  { id: 166, label: "Reel", code: "REEL" },
  { id: 167, label: "Rim", code: "RIM" },
  { id: 168, label: "Rolls", code: "ROL" },
  { id: 169, label: "Room", code: "ROOM" },
  { id: 170, label: "Running Foot", code: "RFT" },
  { id: 171, label: "Running Meter", code: "RMT" },
  { id: 172, label: "Rupees", code: "RS" },
  { id: 173, label: "Sachet", code: "SAC" },
  { id: 174, label: "Seconds", code: "SEC" },
  { id: 175, label: "Semester", code: "SEM" },
  { id: 176, label: "Service", code: "SERVICE" },
  { id: 177, label: "Session", code: "SSN" },
  { id: 178, label: "Sets", code: "SET" },
  { id: 179, label: "Sheet", code: "SHEET" },
  { id: 180, label: "Skins", code: "SKINS" },
  { id: 181, label: "Slants", code: "SLT" },
  { id: 182, label: "Sleves", code: "SLEVES" },
  { id: 183, label: "Spindles", code: "SPLS" },
  { id: 184, label: "Spray", code: "SPRAY" },
  { id: 185, label: "Square Centimeters", code: "SQCM" },
  { id: 186, label: "Square Feet", code: "SQF" },
  { id: 187, label: "Square Gaj", code: "GAJ" },
  { id: 188, label: "Square Gaz", code: "GAZ" },
  { id: 189, label: "Square Inches", code: "SQIN" },
  { id: 190, label: "Square Meters", code: "SQM" },
  { id: 191, label: "Square Yards", code: "SQY" },
  { id: 192, label: "Srm", code: "SARAM" },
  { id: 193, label: "Stickers", code: "STICKER" },
  { id: 194, label: "Stone", code: "STONE" },
  { id: 195, label: "Strips", code: "STRP" },
  { id: 196, label: "Syrup", code: "SYRP" },
  { id: 197, label: "Tablets", code: "TBS" },
  { id: 198, label: "Ten Gross", code: "TGM" },
  { id: 199, label: "Test", code: "TEST" },
  { id: 200, label: "Thousands", code: "THD" },
  { id: 201, label: "Ticket", code: "TKT" },
  { id: 202, label: "Tin", code: "TIN" },
  { id: 203, label: "Tonnes", code: "TON" },
  { id: 204, label: "Trays", code: "TRY" },
  { id: 205, label: "Trp", code: "TRIP" },
  { id: 206, label: "Truck", code: "TRK" },
  { id: 207, label: "Tubes", code: "TUB" },
  { id: 208, label: "Units", code: "UNT" },
  { id: 209, label: "Us Gallons", code: "UGS" },
  { id: 210, label: "Vials", code: "VIAL" },
  { id: 211, label: "Watt", code: "W" },
  { id: 212, label: "Weeks", code: "WEEK" },
  { id: 213, label: "Yards", code: "YDS" },
  { id: 214, label: "Years", code: "YRS" },
];

export const dashboardSingleItemPageMenus = [
  {
    id: 1,
    icon: <FaRegFileLines />,
    title: "Item Details",
  },
  {
    id: 2,
    icon: <TbReportAnalytics />,
    title: "Stock Details",
  },
  {
    id: 3,
    icon: <LuFileUser />,
    title: "Party Wise Report",
  },
  {
    id: 4,
    icon: <TbBuildingWarehouse />,
    title: "Godown",
  },
  {
    id: 5,
    icon: <LuFileUser />,
    title: "Party Wise Prices",
  },
];

export const dateRanges = [
  "Today",
  "Yesterday",
  "This Week",
  "Last Week",
  "Last 7 Days",
  "This Month",
  "Previous Month",
  "Last 30 Days",
  "This Quarter",
  "Previous Quarter",
  "Current Fiscal Year",
  "Previous Fiscal Year",
  "Last 365 Days",
];
